apiVersion: v1
kind: Service
metadata:
  name: changelock-deploy-gate
  namespace: changelock-system
spec:
  selector:
    app: changelock-deploy-gate
  ports:
    - name: https
      port: 443
      targetPort: https
