apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-digest-pinning
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-digest-pinning
      match:
        any:
          - resources:
              kinds: ["Pod"]
      validate:
        message: "Images must be pinned by digest."
        pattern:
          spec:
            containers:
              - image: "?*@sha256:*"
